/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RutaRegistroUsuarioImport } from './routes/rutaRegistroUsuario'
import { Route as RutaRedactarCorreoImport } from './routes/rutaRedactarCorreo'
import { Route as RutaListaUsuariosImport } from './routes/rutaListaUsuarios'
import { Route as RutaListaCorreosImport } from './routes/rutaListaCorreos'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const RutaRegistroUsuarioRoute = RutaRegistroUsuarioImport.update({
  id: '/rutaRegistroUsuario',
  path: '/rutaRegistroUsuario',
  getParentRoute: () => rootRoute,
} as any)

const RutaRedactarCorreoRoute = RutaRedactarCorreoImport.update({
  id: '/rutaRedactarCorreo',
  path: '/rutaRedactarCorreo',
  getParentRoute: () => rootRoute,
} as any)

const RutaListaUsuariosRoute = RutaListaUsuariosImport.update({
  id: '/rutaListaUsuarios',
  path: '/rutaListaUsuarios',
  getParentRoute: () => rootRoute,
} as any)

const RutaListaCorreosRoute = RutaListaCorreosImport.update({
  id: '/rutaListaCorreos',
  path: '/rutaListaCorreos',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/rutaListaCorreos': {
      id: '/rutaListaCorreos'
      path: '/rutaListaCorreos'
      fullPath: '/rutaListaCorreos'
      preLoaderRoute: typeof RutaListaCorreosImport
      parentRoute: typeof rootRoute
    }
    '/rutaListaUsuarios': {
      id: '/rutaListaUsuarios'
      path: '/rutaListaUsuarios'
      fullPath: '/rutaListaUsuarios'
      preLoaderRoute: typeof RutaListaUsuariosImport
      parentRoute: typeof rootRoute
    }
    '/rutaRedactarCorreo': {
      id: '/rutaRedactarCorreo'
      path: '/rutaRedactarCorreo'
      fullPath: '/rutaRedactarCorreo'
      preLoaderRoute: typeof RutaRedactarCorreoImport
      parentRoute: typeof rootRoute
    }
    '/rutaRegistroUsuario': {
      id: '/rutaRegistroUsuario'
      path: '/rutaRegistroUsuario'
      fullPath: '/rutaRegistroUsuario'
      preLoaderRoute: typeof RutaRegistroUsuarioImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/rutaListaCorreos': typeof RutaListaCorreosRoute
  '/rutaListaUsuarios': typeof RutaListaUsuariosRoute
  '/rutaRedactarCorreo': typeof RutaRedactarCorreoRoute
  '/rutaRegistroUsuario': typeof RutaRegistroUsuarioRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/rutaListaCorreos': typeof RutaListaCorreosRoute
  '/rutaListaUsuarios': typeof RutaListaUsuariosRoute
  '/rutaRedactarCorreo': typeof RutaRedactarCorreoRoute
  '/rutaRegistroUsuario': typeof RutaRegistroUsuarioRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/rutaListaCorreos': typeof RutaListaCorreosRoute
  '/rutaListaUsuarios': typeof RutaListaUsuariosRoute
  '/rutaRedactarCorreo': typeof RutaRedactarCorreoRoute
  '/rutaRegistroUsuario': typeof RutaRegistroUsuarioRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rutaListaCorreos'
    | '/rutaListaUsuarios'
    | '/rutaRedactarCorreo'
    | '/rutaRegistroUsuario'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rutaListaCorreos'
    | '/rutaListaUsuarios'
    | '/rutaRedactarCorreo'
    | '/rutaRegistroUsuario'
  id:
    | '__root__'
    | '/'
    | '/rutaListaCorreos'
    | '/rutaListaUsuarios'
    | '/rutaRedactarCorreo'
    | '/rutaRegistroUsuario'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  RutaListaCorreosRoute: typeof RutaListaCorreosRoute
  RutaListaUsuariosRoute: typeof RutaListaUsuariosRoute
  RutaRedactarCorreoRoute: typeof RutaRedactarCorreoRoute
  RutaRegistroUsuarioRoute: typeof RutaRegistroUsuarioRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  RutaListaCorreosRoute: RutaListaCorreosRoute,
  RutaListaUsuariosRoute: RutaListaUsuariosRoute,
  RutaRedactarCorreoRoute: RutaRedactarCorreoRoute,
  RutaRegistroUsuarioRoute: RutaRegistroUsuarioRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/rutaListaCorreos",
        "/rutaListaUsuarios",
        "/rutaRedactarCorreo",
        "/rutaRegistroUsuario"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/rutaListaCorreos": {
      "filePath": "rutaListaCorreos.jsx"
    },
    "/rutaListaUsuarios": {
      "filePath": "rutaListaUsuarios.jsx"
    },
    "/rutaRedactarCorreo": {
      "filePath": "rutaRedactarCorreo.jsx"
    },
    "/rutaRegistroUsuario": {
      "filePath": "rutaRegistroUsuario.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
